/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "← Back": "← 返回",
    "Add step": "添加步骤",
    "and at least all but one of the others to a market and population will grow.": "至少除了其他人之外的所有市场和人口都会增长。",
    "Any help and feedback is welcome :)": "欢迎任何帮助和反馈:)",
    "Build": "建造",
    "Buildings": "建筑物",
    "Colorblind Mode": "色盲模式",
    "Demand buildings": "需求建筑",
    "Display trade routes": "显示贸易路线",
    "Hire trader": "聘请交易员",
    "market": "市场",
    "Market place": "市场",
    "Name": "名称",
    "New route": "新路线",
    "Next →": "下一个 →",
    "Population needs": "人口需求",
    "Provide all of": "提供所有",
    "restart": "重新开始",
    "Routes": "路线",
    "Skip": "跳过",
    "Take a tour and have fun if you can": "如果可以的话，参观并玩得开心",
    "This is an ongoing game focused on market systems and trade mechanics (wow, sexy).": "这是一款专注于市场系统和交易机制的持续游戏（哇，性感）。",
    "Trade routes": "贸易路线",
    "Traders": "交易员",
    "Welcome!": "欢迎！",
    "Workshops": "车间",
    "Actually, there are many other things like workshops, demand buildings and new discoveries over time!": "实际上，随着时间的推移，还有许多其他的东西，比如车间、需求建筑和新发现！",
    "Add a new step to the route": "向路线添加新步骤",
    "All done!": "全部完成！",
    "Almost done!": "快完成了！",
    "auto": "自动",
    "But that's it for now.": "但这就是现在。",
    "Buy cheap and sell to a higher price to earn money.": "买便宜卖到更高的价格来赚钱。",
    "By doing this you tell traders to leave the market with these 3 resources, meaning buying them.": "通过这样做，您告诉交易者带着这 3 种资源离开市场，即购买它们。",
    "By leaving the slots empty you tell traders to leave the market without resource, meaning selling everything they have.": "通过将插槽留空，您告诉交易者在没有资源的情况下离开市场，这意味着出售他们拥有的一切。",
    "Click 3 times on the orange resource in the market resources list": "在市场资源列表中点击3次橙色资源",
    "Click on the market connected to the purple resource": "点击与紫色资源相连的市场",
    "Click on the market to select it": "点击市场以选择它",
    "Create a new route by clicking on the Add button": "通过单击“添加”按钮创建新路线",
    "Destroy": "摧毁",
    "Don't touch anything": "不要碰任何东西",
    "Done": "完毕",
    "Each day, resource sites connected to a market will work on exploiting resource. And when they finished, they put a new resource on sale in the market.": "每天，与市场相连的资源站点将致力于开发资源。完成后，他们将一种新资源投放市场。",
    "Exploitation": "开发",
    "Go to the next day": "去第二天",
    "Great! The trader placed orders on the market according to the first step of the route and is waiting for them to be resolved.": "伟大的！交易者根据路线的第一步在市场上下单，等待解决。",
    "Great.": "伟大的。",
    "Hint: to cancel an order click on the resource slot": "提示：要取消订单，请单击资源槽",
    "Hire a trader and assign him the trade route": "雇用一名交易员并为他分配贸易路线",
    "I need you": "我需要你",
    "If the satisfaction is high enough for long enough then the population will start to settle around the market and gradually generate demand.": "如果满意度足够高并且足够长的时间，那么人口将开始在市场周围定居并逐渐产生需求。",
    "If there is stock on the market but no buyer then the price of the resource will begin to decrease.": "如果市场上有库存但没有买家，那么资源的价格将开始下降。",
    "If you like it and want more, consider giving me a boost: comment, share, donate :)": "如果您喜欢它并想要更多，请考虑给我一个助力：评论、分享、捐赠 :)",
    "In 'auto' mode workshop produces only when it is profitable. If there are several production lines in 'auto' or 'on' mode then the most profitable is selected.": "在“自动”模式下，车间只有在盈利时才会生产。如果有多条生产线处于“自动”或“开启”模式，则选择最有利可图的。",
    "It's an important source of information, for example to monitor the activity of an exploitation or to know the supply and demand in a market.": "它是重要的信息来源，例如监控开采活动或了解市场的供需情况。",
    "Keep an eye on your money.": "留意你的钱。",
    "Manage supply and demand in markets to vary prices.": "管理市场的供求关系以改变价格。",
    "Name the route 'Orange'": "将路线命名为“橙色”",
    "Now we are going to define a trade route to buy orange resources on a market and sell them to the other one": "现在我们要定义一条贸易路线，在市场上购买橙色资源并将其出售给另一个市场",
    "Now, find and zoom on a purple one": "现在，找到并放大一个紫色的",
    "Now, find and zoom on an orange site": "现在，找到并放大橙色站点",
    "owned": "拥有",
    "Place the market close to the orange site so they are connected": "将市场靠近橙色站点，以便它们连接起来",
    "Place the market near the purple site": "将市场放在紫色地点附近",
    "Population": "人口",
    "Providing all the resources that population needs at a low price will increase satisfaction for the market.": "以低廉的价格提供人口所需的所有资源将增加市场的满意度。",
    "route": "路线",
    "route 1": "路线 1",
    "Select a market on the map": "在地图上选择一个市场",
    "Select the market connected to the orange exploitation": "选择与橙色开发相关的市场",
    "Select the Trade Routes menu": "选择贸易路线菜单",
    "Select the Traders menu": "选择交易者菜单",
    "Step by step or auto run. You can change the auto run speed by clicking on the speed indicator.": "逐步或自动运行。您可以通过单击速度指示器来更改自动运行速度。",
    "Thanks!": "谢谢！",
    "The route is created with a first step selected by default. A route step defines in which market to go and which resources to buy and sell.": "默认情况下选择第一步创建路线。路线步骤定义了去往哪个市场以及买卖哪些资源。",
    "Then he will start again from the first step.": "然后他将从第一步重新开始。",
    "These are the resources that the population needs.": "这些是人们需要的资源。",
    "This is the world map.": "这是世界地图。",
    "To associate a market with the selected step simply click on it.": "要将市场与选定的步骤相关联，只需单击它。",
    "to associate it with the step": "将其与步骤相关联",
    "to find it more easily.": "更容易找到它。",
    "Trade route": "商路",
    "We are going to build a market.": "我们要建立一个市场。",
    "We are going to hire a trader to follow our trade route.": "我们将聘请一名交易员来遵循我们的贸易路线。",
    "We can switch to auto run mode until orange exploitation produces the 3 resources.": "我们可以切换到自动运行模式，直到橙色开发产生 3 个资源。",
    "We have to create a market and provide both purple and orange resources to bring people in.": "我们必须创造一个市场，提供紫色和橙色的资源来吸引人们。",
    "When he bought the 3 resources, he tries to sell them to the second market.": "当他购买了这 3 种资源时，他试图将它们出售给第二个市场。",
    "Workshop": "作坊",
    "You can control the course of time here.": "您可以在这里控制时间进程。",
    "You can move by clicking and dragging or zoom using the mouse wheel": "您可以通过单击并拖动或使用鼠标滚轮缩放来移动",
    "You can see some resource sites on the map.": "您可以在地图上看到一些资源站点。",
    "You can see the details of the selected element here.": "您可以在此处查看所选元素的详细信息。",
    "You must see a dashed line indicating the connection. Click to build.": "您必须看到一条表示连接的虚线。点击建造。",
    "click to empty": "点击清空",
    "demand": "要求",
    "Leave the market with:": "离开市场：",
    "Market": "市场",
    "Must be connected to a market place to be exploited": "必须连接到要开发的市场",
    "need": "需要",
    "price": "价格",
    "Resource site": "资源站点",
    "Satisfaction": "满意",
    "Select market resources": "选择市场资源",
    "stock": "库存",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "a": "a",
    "b": "b",
    "c": "c",
    "d": "d",
    "e": "e",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Traders : ": "商人 : ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) coins$/, '$1 金币'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Step ([\d\.,]+)$/, '步骤 $1'],
    [/^trader ([\d\.,]+)$/, '商人 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);